name: dev_check
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: execute check styles
        run: python tests/code-style/check.py
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
            node-version: 14
      - name: Run unit tests
        run: |
          npm install -g grunt-cli node-qunit-puppeteer
          npm install --prefix build
          grunt --gruntfile build/Gruntfile.js develop
          node-qunit-puppeteer tests/common/api/api.html
          node-qunit-puppeteer tests/cell/shortcuts/shortcuts.html
          node-qunit-puppeteer tests/cell/spreadsheet-calculation/FormulaTests.html
          node-qunit-puppeteer tests/cell/spreadsheet-calculation/PivotTests.html
          node-qunit-puppeteer tests/cell/spreadsheet-calculation/CopyPasteTests.html
          node-qunit-puppeteer tests/cell/spreadsheet-calculation/SheetStructureTests.html
          node-qunit-puppeteer tests/cell/spreadsheet-calculation/autoFilterTests.html
          node-qunit-puppeteer tests/cell/spreadsheet-calculation/UserProtectedRangesTest.html
          node-qunit-puppeteer tests/cell/spreadsheet-calculation/FormulaTrace.html
          node-qunit-puppeteer tests/word/unit-tests/paragraphContentPos.html
          node-qunit-puppeteer tests/word/content-control/block-level/cursorAndSelection.html
          node-qunit-puppeteer tests/word/content-control/inline-level/cursorAndSelection.html
          node-qunit-puppeteer tests/word/document-calculation/floating-position/drawing.html
          node-qunit-puppeteer tests/word/document-calculation/paragraph.html
          node-qunit-puppeteer tests/word/document-calculation/table/correctBadTable.html
          node-qunit-puppeteer tests/word/document-calculation/table/flowTablePosition.html
          node-qunit-puppeteer tests/word/document-calculation/table/pageBreak.html
          node-qunit-puppeteer tests/word/document-calculation/textShaper/textShaper.html
          node-qunit-puppeteer tests/word/document-calculation/text-hyphenator/text-hyphenator.html
          node-qunit-puppeteer tests/word/forms/forms.html
          node-qunit-puppeteer tests/word/forms/complexForm.html
          node-qunit-puppeteer tests/word/numbering/numberingApplicator.html
          node-qunit-puppeteer tests/word/numbering/numberingCalculation.html
          node-qunit-puppeteer tests/word/api/api.html
          node-qunit-puppeteer tests/word/api/textInput.html
          node-qunit-puppeteer tests/word/styles/displayStyle.html
          node-qunit-puppeteer tests/word/styles/paraPr.html
          node-qunit-puppeteer tests/word/styles/styleApplicator.html
          node-qunit-puppeteer tests/word/plugins/pluginsApi.html
          node-qunit-puppeteer tests/word/merge-documents/mergeDocuments.html
          node-qunit-puppeteer tests/word/shortcuts/shortcuts.html
          node-qunit-puppeteer tests/slide/shortcuts/shortcuts.html
  builder-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
            node-version: 12
      - name: Run builder tests
        run: |
           npm install -g grunt-cli
           npm install --prefix build
           grunt --level=WHITESPACE_ONLY --base build --gruntfile build/Gruntfile.js
           docker run -v $PWD/deploy/sdkjs/common:/opt/onlyoffice/documentbuilder/sdkjs/common \
                      -v $PWD/deploy/sdkjs/word:/opt/onlyoffice/documentbuilder/sdkjs/word \
                      -v $PWD/deploy/sdkjs/cell:/opt/onlyoffice/documentbuilder/sdkjs/cell \
                      -v $PWD/deploy/sdkjs/slide:/opt/onlyoffice/documentbuilder/sdkjs/slide \
                      onlyoffice/doc-builder-testing:develop-latest rake rspec_critical
